#!/usr/bin/env bash

function getarg() { 
  local varibale_name="$1"
  local next_arg="${BASH_ARGV[$[BASH_ARGC-OPTIND]]}"
  declare -g "${varibale_name}"=""
  if [[ $next_arg =~ ^-$ ]] || [[ $next_arg =~ ^[^-] ]]; then
    declare -g "${varibale_name}"="${next_arg}"
    let "OPTIND++"
  fi
}

function read_rc_file() {
  if [[ -r ~/.$(basename ${0})rc ]];then
    while IFS='=' read -r key value; do
      eval $key="$value"
    done <<<"$( cat ~/.$(basename ${0})rc \
      | sed -e'/^[a-zA-Z0-9_]*=/!d' -e'/^#/d' -e'/^ *$/d' \
    )"
  fi
}

function get_password() {
  if [[ -n "$PASSWORD" ]];then
    echo "$PASSWORD"
  elif [[ -n "$PASSWORD_COMMAND" ]];then
    echo "$($PASSWORD_COMMAND)"
  else
    read -r -s -p "enter password: "
    echo "$REPLY"
  fi
}

